25062021/Models/ErrorViewModel.cs
using System;

namespace tranning.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

25062021/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tranning.Models;

namespace tranning.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

25062021/Controllers/RookieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc;


namespace _24062021.Controllers
{
    public class RookieController : Controller
    {
        static List<PersonModel> members = new List<PersonModel>{
            new PersonModel{
                Id = new Guid("b43021a7-8a20-445f-9948-90522286e9a0"),
                FirstName = "A",
                LastName = "Nguyen Van",
                BirthPlace = "Hai Phong",
                Gender = "male",
                DateOfBirth = new DateTime(1992,01,02),
            },
            new PersonModel{
                Id = new Guid("de7ee905-b823-4c8f-8977-0b80e110cfbd"),
                FirstName = "B",
                LastName = "Nguyen Van",
                BirthPlace = "Quang Ninh",
                Gender = "Male",
                DateOfBirth = new DateTime(1992,01,01),
            },
            new PersonModel{
                Id = new Guid("8e61248e-9c86-44f4-9165-86efd0f18d67"),
                FirstName = "C",
                LastName = "Nguyen Van",
                BirthPlace = "Hai Phong",
                Gender = "male",
                DateOfBirth = new DateTime(1992,01,01),
            },
            new PersonModel{
                Id = new Guid("e9fd825a-58ca-4f26-9d0d-8e184d6bf6f2"),
                FirstName = "D",
                LastName = "Nguyen Van",
                BirthPlace = "Ha Noi",
                Gender = "Female",
                DateOfBirth = new DateTime(2001,12,02),
            },
            new PersonModel{
                Id = new Guid("e0ae2d15-7d3a-4cd9-9546-7ab7a474700b"),
                FirstName = "E",
                LastName = "Nguyen Van",
                BirthPlace = "ha noi",
                Gender = "Male",
                DateOfBirth = new DateTime(1993,07,02),
            },
            new PersonModel{
                Id = new Guid("e9cc5b59-14d0-48f2-8b99-c06a38d4954d"),
                FirstName = "F",
                LastName = "Nguyen Van",
                BirthPlace = "Ha Noi",
                Gender = "Male",
                DateOfBirth = new DateTime(2000,01,02),
            },
            new PersonModel{
                Id = new Guid("05faa4ba-9b12-43a5-bdf3-d2a4d4d2e05e"),
                FirstName = "G",
                LastName = "Nguyen Van",
                BirthPlace = "Hai Phong",
                Gender = "Female",
                DateOfBirth = new DateTime(2000,01,02),
            },
        };

        public IActionResult ViewList()
        {
            return View(members);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("FirstName", "LastName", "Gender", "DateOfBirth", "PhoneNumber", "BirthPlace", "IsGraduated", "Email")] PersonModel person)
        {
            if (ModelState.IsValid)
            {
                person.Id = new Guid();
                members.Add(person);
                return RedirectToAction(nameof(ViewList));
            }
            return View("Fail");
        }

        public IActionResult Edit(Guid id)
        {
            var person = members.FirstOrDefault(x => x.Id == id);
            return View(person);
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id", "FirstName", "LastName", "Gender", "DateOfBirth", "PhoneNumber", "BirthPlace", "IsGraduated", "Email")] PersonModel person)
        {
            var findPerson = members.FindIndex(x => x.Id == person.Id);
            if (findPerson != -1 && ModelState.IsValid)
            {
                members[findPerson] = person;
                return RedirectToAction(nameof(ViewList));
            }
            return View("Fail");
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            var findPerson = members.FindIndex(x => x.Id == id);
            if (findPerson != -1)
            {
                members.RemoveAt(findPerson);
            }
             return View("Fail");
        }
    }
}

25062021/Views/Rookie/ViewList.cshtml
@model List<PersonModel>
@{
    ViewBag.Title = "View List Person";
    var index = 1;
}
<script src="~/js/view_list.js"></script>
<div class="row">
    <div class="col-10">
        <h3>List Person in Rookie</h3>
    </div>
    <div class="col-2">
        <a class="btn btn-dark" href="@Url.Action("Create")" role="button">Add New Person</a>
    </div>
</div>

<br>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">STT</th>
            <th scope="col">FullName</th>
            <th scope="col">Gender</th>
            <th scope="col">PhoneNumber</th>
            <th scope="col">BirthPlace</th>
            <th scope="col">Age</th>
            <th scope="col">IsGraduated</th>
            <th scope="col">Email</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@index</th>
                <td>@item.FullName</td>
                <td>@item.Gender.ToLower()</td>
                <td>@item.PhoneNumber</td>
                <td>@item.BirthPlace.ToUpper()</td>
                <td>@item.Age</td>
                @if (@item.IsGraduated)
                {
                    <td>Done</td>
                }
                else
                {
                    <td>Not Yet</td>
                }
                <td>@item.Email</td>
                <td><a class="btn btn-secondary" href="@Url.Action("Edit" , new {id = @item.Id })" , role="button">Edit</a>
                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#confirmDelete"
                    onclick="Confirm('@(item.Id)', '@(item.FullName)');">
                        Delete
                    </button>
                </td>
            </tr>

            index++;
        }
        
    </tbody>


    <!-- Modal -->
    <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Đu diu goan tu đi lít</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    We will be so sad
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    @using (Html.BeginForm("Delete", "Rookie", FormMethod.Post))
                    {
                        <input type="hidden" id="Id" name="Id" />
                        <button type="submit" class="btn btn-primary">Yes</button>
                    }             
                </div>
            </div>
        </div>
    </div>
</table>

25062021/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tranning</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tranning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - tranning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>